### PR TITLE
Fix interactive command examples not rendering as monospace

### PR DESCRIPTION
**Pull request by Pyker**

### CODE REVIEW

**Comment by Pyker** [comment]
@antirez Any update on the status of this PR?

**Comment by wodim** [comment]
I was about to write this PR... Without it, command examples use Times New Roman on Windows!

**Comment by Pyker** [comment]
I find it impressive that such a simple change is still pending after nearly 3 years.

**Comment by acataluddi** [comment]
Hi @oranagra,  

can anyone merge this trivial PR, please? It would be very beneficial for people reading the documentation.

Thanks

**Review by itamarhaber — APPROVED** [review]

**Comment by acataluddi** [comment]
Thank you guys! Much appreciated.

Adriano C.

**Comment by oranagra** [comment]
sorry for the delays.
this should already be effective. let me know if for some reason it doesn't work as expected.

**Comment by Pyker** [comment]
Thank you! It works great, as can been seen in <https://redis.io/commands/set#examples>.

**Pull request merged**
